name: extended_type
description: Collection of platform agnostic types that can be converted from/to JSON and used in databases and UI.
version: 2.1.0
homepage: https://github.com/Colossus-Services/extended_type

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  swiss_knife: ^3.2.0


dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
  #test_coverage: ^0.4.2
