name: extended_type
description: Collection of platform agnostic types that can be converted from/to JSON and used in databases and UI.
version: 1.0.1
homepage: https://github.com/Colossus-Services/extended_type

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.18
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.4.2
