name: extended_type
description: Collection of platform agnostic types that can be converted from/to JSON and used in databases and UI.
version: 2.0.1
homepage: https://github.com/Colossus-Services/extended_type

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.0.6
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
  #test_coverage: ^0.4.2
